basePath: /
definitions:
  dto.CourseResponse:
    properties:
      description:
        type: string
      id:
        type: string
      imgURL:
        type: string
      name:
        type: string
    type: object
  dto.OrderRequest:
    properties:
      course_id:
        type: string
      userId:
        type: string
    type: object
  dto.OrderResponse:
    properties:
      error: {}
      status:
        type: integer
    type: object
  dto.OrderReviewRequest:
    properties:
      comment:
        type: string
      order_id:
        type: string
      rating:
        type: integer
    type: object
  dto.ReviewResponse:
    properties:
      comment:
        type: string
      course_name:
        type: string
      created_at:
        type: string
      rating:
        type: integer
      user_name:
        type: string
    type: object
  dto.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dto.SignInResponse:
    properties:
      accessToken:
        type: string
    type: object
  dto.SignUpRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  dto.SignUpResponse:
    properties:
      accessToken:
        type: string
    type: object
  entity.Order:
    properties:
      courseId:
        type: string
      id:
        type: string
      userId:
        type: string
    type: object
  status.Response:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: a course service api in golang
  title: Course Service API
  version: "1.0"
paths:
  /auth/sign-in:
    post:
      consumes:
      - application/json
      parameters:
      - description: body param
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SignInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/status.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/status.Response'
      summary: sign in user
      tags:
      - authorization
  /auth/sign-up:
    post:
      consumes:
      - application/json
      parameters:
      - description: body param
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SignUpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/status.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/status.Response'
      summary: sign up user
      tags:
      - authorization
  /courses:
    get:
      description: get all courses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.CourseResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/status.Response'
      summary: Get all courses
      tags:
      - courses
  /courses/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: path param
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CourseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/status.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/status.Response'
      summary: get
      tags:
      - courses
  /order:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Order'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/status.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/status.Response'
      security:
      - ApiKeyAuth: []
      summary: get user's orders
      tags:
      - order
    post:
      consumes:
      - application/json
      description: create order by course id and user id
      parameters:
      - description: order req
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.OrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.OrderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/status.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/status.Response'
      security:
      - ApiKeyAuth: []
      summary: create order
      tags:
      - order
  /order/review:
    delete:
      consumes:
      - application/json
      parameters:
      - description: path param
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/status.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/status.Response'
      security:
      - ApiKeyAuth: []
      summary: delete review by id
      tags:
      - order
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.ReviewResponse'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/status.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/status.Response'
      security:
      - ApiKeyAuth: []
      summary: get all reviews
      tags:
      - order
    post:
      consumes:
      - application/json
      parameters:
      - description: review req
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.OrderReviewRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/status.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/status.Response'
      security:
      - ApiKeyAuth: []
      summary: add review to order
      tags:
      - order
swagger: "2.0"
